language: cpp
env:
  global:
  - PACKAGE_NAME=GlobalProtect
# safelist
dist: xenial
branches:
  only:
  - master
# Recursive Cloning
git:
  depth: false
before_install:
- sudo apt update
- sudo apt -y install fakeroot debhelper qt5-default qttools5-dev libqt5websockets5-dev
- sudo pip install git-archive-all
- export BUILD_VERSION=$(date "+%Y%m%d").$TRAVIS_BUILD_NUMBER
- export PACKAGE_NAME_VERSION=$PACKAGE_NAME.$BUILD_VERSION.deb
script:
- git-archive-all --force-submodules --prefix=globalprotect-openconnect-1.3.0/ ../globalprotect-openconnect_1.3.0.orig.tar.gz
- cd ..
- tar -xzvf globalprotect-openconnect_1.3.0.orig.tar.gz
- cd globalprotect-openconnect-1.3.0
- fakeroot dpkg-buildpackage -uc -us -sa 2>&1 | tee ../build.log
- ls
# mv $PACKAGE_NAME.deb $PACKAGE_NAME_VERSION
after_success:
- echo Done!
# ls -l $PACKAGE_NAME_VERSION
# md5sum $PACKAGE_NAME_VERSION
# dpkg --contents $PACKAGE_NAME_VERSION
