language: cpp
env:
  global:
  - PACKAGE_NAME=globalprotect-openconnect_1.3.0
# safelist
branches:
  only:
  - master
dist: xenial

addons:
  apt:
    packages:
    - fakeroot
    - debhelper
    - qt5-default
    - qttools5-dev
    - libqt5websockets5-dev
env:
    - QT_CI_PACKAGES=qt.qt5.5132.gcc_64,qt.qt5.5132.qtwebengine PATH="$TRAVIS_BUILD_DIR/Qt/5.13.2/gcc_64/bin:${PATH}"

# Recursive Cloning
git:
  depth: false

before_install:
- sudo pip install git-archive-all
- export BUILD_VERSION=$(date "+%Y%m%d").$TRAVIS_BUILD_NUMBER
- export PACKAGE_NAME_VERSION=$PACKAGE_NAME.$BUILD_VERSION.deb
- sudo apt -q update
script:
- git-archive-all --force-submodules --prefix=globalprotect-openconnect-1.3.0/ ../globalprotect-openconnect_1.3.0.orig.tar.gz
- cd ..
- tar -xzvf globalprotect-openconnect_1.3.0.orig.tar.gz
- cd globalprotect-openconnect-1.3.0
- fakeroot dpkg-buildpackage -uc -us -sa 2>&1 | tee ../build.log
- ls
- cd ..
- ls
# mv $PACKAGE_NAME.deb $PACKAGE_NAME_VERSION
after_success:
- echo Done!
# ls -l $PACKAGE_NAME_VERSION
# md5sum $PACKAGE_NAME_VERSION
# dpkg --contents $PACKAGE_NAME_VERSION
